server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/fleetty/spring-config-repository.git
          default-label: master
          username: develop.kalmykov@gmail.com
          password: acer007Gitlub
          cloneOnStart: true

#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///home/nikolay/Projects/EasyFleet/config-server-git
#          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: "*"